"""empty message

Revision ID: 585bbe35b162
Revises: 9d986e472158
Create Date: 2016-08-11 23:46:23.533488

"""

# revision identifiers, used by Alembic.
revision = '585bbe35b162'
down_revision = '9d986e472158'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_traceroute__sub_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_traceroute__sub_result')
    ### end Alembic commands ###
