"""empty message

Revision ID: 9605afa9362b
Revises: 9cc92a4a3ea7
Create Date: 2016-08-12 00:29:10.725330

"""

# revision identifiers, used by Alembic.
revision = '9605afa9362b'
down_revision = '9cc92a4a3ea7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_result', sa.Column('destination', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('input_destination', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('input_source', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('ip_packet_size', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('ip_transport_protocol', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('measurement_agent', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('subject_type', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('time_interval', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('tool_name', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('trace_max_ttl', sa.String(length=50), nullable=True))
    op.add_column('main_result', sa.Column('uri', sa.String(length=128), nullable=True))
    op.add_column('main_result', sa.Column('url', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_result', 'url')
    op.drop_column('main_result', 'uri')
    op.drop_column('main_result', 'trace_max_ttl')
    op.drop_column('main_result', 'tool_name')
    op.drop_column('main_result', 'time_interval')
    op.drop_column('main_result', 'subject_type')
    op.drop_column('main_result', 'source')
    op.drop_column('main_result', 'measurement_agent')
    op.drop_column('main_result', 'ip_transport_protocol')
    op.drop_column('main_result', 'ip_packet_size')
    op.drop_column('main_result', 'input_source')
    op.drop_column('main_result', 'input_destination')
    op.drop_column('main_result', 'destination')
    ### end Alembic commands ###
