"""empty message

Revision ID: 9a8e34a5c26e
Revises: 585bbe35b162
Create Date: 2016-08-11 23:47:01.641244

"""

# revision identifiers, used by Alembic.
revision = '9a8e34a5c26e'
down_revision = '585bbe35b162'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('wagt_name', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
