"""empty message

Revision ID: 9bc7c0dec908
Revises: c31fe65392d0
Create Date: 2016-08-12 00:40:52.216377

"""

# revision identifiers, used by Alembic.
revision = '9bc7c0dec908'
down_revision = 'c31fe65392d0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_result', 'ip_packet_size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_result', sa.Column('ip_packet_size', mysql.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
