"""empty message

Revision ID: 9cc92a4a3ea7
Revises: 9a8e34a5c26e
Create Date: 2016-08-12 00:13:39.195272

"""

# revision identifiers, used by Alembic.
revision = '9cc92a4a3ea7'
down_revision = '9a8e34a5c26e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_result', 'url')
    op.drop_column('main_result', 'subject_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_result', sa.Column('subject_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('main_result', sa.Column('url', mysql.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###
