"""empty message

Revision ID: 9d986e472158
Revises: None
Create Date: 2016-08-11 23:34:08.543400

"""

# revision identifiers, used by Alembic.
revision = '9d986e472158'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_traceroute_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_result',
    sa.Column('metadata_key', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('metadata_key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('wagt_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('main_result')
    op.drop_table('individual_traceroute_result')
    ### end Alembic commands ###
